// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdjzgyeurdijzfwvfgtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkanpneWV1cmRpanpmd3ZmZ3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTkzNjksImV4cCI6MjA2OTQ3NTM2OX0.DcLaofEfewtbIp-wT8sfFTSNhFexfIclVDBLQ2yVnkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});